data <- read.table("household_power_consumption.txt", header = TRUE, sep=";" )
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data1 <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
data1$Global_active_power <- as.numeric(as.character(data1$Global_active_power))
plot(data1$Time, data1$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.copy(png,filename="plot2.png",width = 480, height = 480, units = "px")
dev.off ()
